# syntax=docker/dockerfile:1
FROM alpine:3.21

RUN set -x && \
    apk add cmake py3-pip g++ make samurai git upx && \
    pip install conan --break-system-packages

RUN --mount=type=cache,target=/root/.conan2 \
    conan profile detect --force

COPY conanfile.txt /sources/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    mkdir -p /build && \
    cd /build && \
    conan install /sources --output-folder=. --build=missing

COPY . /sources/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    cd /build && \
    cmake /sources -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja && \
    cmake --build . && \
    upx --best --lzma cli/openapi-yagen
