# syntax=docker/dockerfile:1
FROM navrocky/buildroot-uclibc-toolchain:i686-2023.11.1

RUN set -x && \
    apt-get update && \
    apt-get -y install cmake make python3-pip ninja-build git upx-ucl && \
    pip install conan --break-system-packages

RUN --mount=type=cache,target=/root/.conan2 \
    conan profile detect --force && sed -i 's/x86_64/x86/g' ~/.conan2/profiles/default

COPY conanfile.txt /sources/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    mkdir -p /build && \
    cd /build && \
    conan install /sources -s compiler.cppstd=20 --output-folder=. --build=missing

COPY . /sources/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    cd /build && \
    cmake /sources -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja && \
    cmake --build . && \
    upx --best --lzma cli/openapi-yagen
