# syntax=docker/dockerfile:1
FROM emscripten/emsdk:3.1.64

RUN set -x && \
    apt-get update && \
    apt-get -y install python3-pip ninja-build && \
    pip install conan

RUN --mount=type=cache,target=/root/.conan2 \
    conan profile detect --force

COPY wasm/conanfile.txt wasm/conan-emscripten.profile /sources/wasm/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    mkdir -p /build && \
    cd /build && \
    conan install /sources/wasm -s compiler.cppstd=20 --output-folder=. --build=missing \
        --profile:build=default --profile:host=/sources/wasm/conan-emscripten.profile

COPY . /sources/

RUN --mount=type=cache,target=/root/.conan2 set -x && \
    cd /build && \
    cmake /sources -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja && \
    cmake --build . --target openapi-yagen-wasm
